import {
  PATH_ADD,
  PATH_SUBTRACT,
  PATH_MULTIPLY,
  PATH_DIVIDE,
  PATH_COMPARE,
  PATH_MISSING_NUMBER,
  PATH_TRUE_FALSE,
  PATH_NUMBER_SEQUENCE,
  PATH_TIME_CHALLENGE,
} from '@/constants';
import type { GameCardType } from '@/types';
import { GameType } from '@/types';

export const GAME_CARDS: GameCardType[] = [
  {
    emoji: '➕',
    path: PATH_ADD,
    color: '#FF6B6B',
    gameType: GameType.add,
    title: 'games.addition',
    description: 'games.additionDescription',
  },
  {
    emoji: '➖',
    color: '#4ECDC4',
    path: PATH_SUBTRACT,
    title: 'games.subtraction',
    gameType: GameType.subtract,
    description: 'games.subtractionDescription',
  },
  {
    emoji: '✖️',
    color: '#95E1D3',
    path: PATH_MULTIPLY,
    title: 'games.multiply',
    gameType: GameType.multiply,
    description: 'games.multiplyDescription',
  },
  {
    emoji: '➗',
    path: PATH_DIVIDE,
    color: '#FFD93D',
    title: 'games.divide',
    gameType: GameType.divide,
    description: 'games.divideDescription',
  },
  {
    emoji: '⚖️',
    color: '#6C5CE7',
    path: PATH_COMPARE,
    title: 'games.compare',
    gameType: GameType.compare,
    description: 'games.compareDescription',
  },
  {
    emoji: '⁉️',
    color: '#F39C12',
    path: PATH_MISSING_NUMBER,
    title: 'games.missingNumber',
    gameType: GameType.missingNumber,
    description: 'games.missingNumberDescription',
  },
  {
    emoji: '✅',
    color: '#2ECC71',
    path: PATH_TRUE_FALSE,
    title: 'games.trueFalse',
    gameType: GameType.trueFalse,
    description: 'games.trueFalseDescription',
  },
  {
    emoji: '🔢',
    color: '#9B59B6',
    path: PATH_NUMBER_SEQUENCE,
    title: 'games.numberSequence',
    gameType: GameType.numberSequence,
    description: 'games.numberSequenceDescription',
  },
  {
    emoji: '⏰',
    color: '#E74C3C',
    path: PATH_TIME_CHALLENGE,
    title: 'games.timeChallenge',
    gameType: GameType.timeChallenge,
    description: 'games.timeChallengeDescription',
  },
];
